---

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  monitored_conditions:
    - precip_probability
    - icon
    - temperature_low
    - temperature_high
    - temperature

- platform: season

- platform: template
  sensors:
    forecast_0:
      friendly_name: Today
      entity_id: sensor.time
      value_template: >
        {{ states.sensor.dark_sky_daytime_high_temperature_0d.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_0d.state|round(0)}}°
      icon_template: >-
        {% if is_state("sensor.dark_sky_icon", "clear-day") %}
          mdi:weather-sunny
        {% elif is_state("sensor.dark_sky_icon", "clear-night") %}
          mdi:weather-night
        {% elif is_state("sensor.dark_sky_icon", "cloudy") %}
          mdi:weather-cloudy
        {% elif is_state("sensor.dark_sky_icon", "rain") %}
          mdi:weather-pouring
        {% elif is_state("sensor.dark_sky_icon", "sleet") %}
          mdi:weather-snowy-rain
        {% elif is_state("sensor.dark_sky_icon", "snow") %}
          mdi:weather-snowy
        {% elif is_state("sensor.dark_sky_icon", "wind") %}
          mdi:weather-windy
        {% elif is_state("sensor.dark_sky_icon", "fog") %}
          mdi:weather-fog
        {% elif is_state("sensor.dark_sky_icon", "partly-cloudy-day") %}
          mdi:weather-partlycloudy
        {% elif is_state("sensor.dark_sky_icon", "partly-cloudy-night") %}
          mdi:weather-partlycloudy
        {% else %}
          error
        {% endif %}

    forecast_1:
      friendly_name: Tomorrow
      entity_id: sensor.time
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_1d.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_1d.state|round(0)}}°
      icon_template: >-
        {% if is_state("sensor.dark_sky_icon_1d", "clear-day") %}
          mdi:weather-sunny
        {% elif is_state("sensor.dark_sky_icon_1d", "clear-night") %}
          mdi:weather-night
        {% elif is_state("sensor.dark_sky_icon_1d", "cloudy") %}
          mdi:weather-cloudy
        {% elif is_state("sensor.dark_sky_icon_1d", "rain") %}
          mdi:weather-pouring
        {% elif is_state("sensor.dark_sky_icon_1d", "sleet") %}
          mdi:weather-snowy-rain
        {% elif is_state("sensor.dark_sky_icon_1d", "snow") %}
          mdi:weather-snowy
        {% elif is_state("sensor.dark_sky_icon_1d", "wind") %}
          mdi:weather-windy
        {% elif is_state("sensor.dark_sky_icon_1d", "fog") %}
          mdi:weather-fog
        {% elif is_state("sensor.dark_sky_icon_1d", "partly-cloudy-day") %}
          mdi:weather-partlycloudy
        {% elif is_state("sensor.dark_sky_icon_1d", "partly-cloudy-night") %}
          mdi:weather-partlycloudy
        {% else %}
          error
        {% endif %}

    forecast_2:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
        {{ date | timestamp_custom("%A") }}
      entity_id: sensor.time
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_2d.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_2d.state|round(0)}}°
      icon_template: >-
        {% if is_state("sensor.dark_sky_icon_2d", "clear-day") %}
          mdi:weather-sunny
        {% elif is_state("sensor.dark_sky_icon_2d", "clear-night") %}
          mdi:weather-night
        {% elif is_state("sensor.dark_sky_icon_2d", "cloudy") %}
          mdi:weather-cloudy
        {% elif is_state("sensor.dark_sky_icon_2d", "rain") %}
          mdi:weather-pouring
        {% elif is_state("sensor.dark_sky_icon_2d", "sleet") %}
          mdi:weather-snowy-rain
        {% elif is_state("sensor.dark_sky_icon_2d", "snow") %}
          mdi:weather-snowy
        {% elif is_state("sensor.dark_sky_icon_2d", "wind") %}
          mdi:weather-windy
        {% elif is_state("sensor.dark_sky_icon_2d", "fog") %}
          mdi:weather-fog
        {% elif is_state("sensor.dark_sky_icon_2d", "partly-cloudy-day") %}
          mdi:weather-partlycloudy
        {% elif is_state("sensor.dark_sky_icon_2d", "partly-cloudy-night") %}
          mdi:weather-partlycloudy
        {% else %}
          error
        {% endif %}

    forecast_3:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
        {{ date | timestamp_custom("%A") }}
      entity_id: sensor.time
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_3d.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_3d.state|round(0)}}°
      icon_template: >-
        {% if is_state("sensor.dark_sky_icon_3d", "clear-day") %}
          mdi:weather-sunny
        {% elif is_state("sensor.dark_sky_icon_3d", "clear-night") %}
          mdi:weather-night
        {% elif is_state("sensor.dark_sky_icon_3d", "cloudy") %}
          mdi:weather-cloudy
        {% elif is_state("sensor.dark_sky_icon_3d", "rain") %}
          mdi:weather-pouring
        {% elif is_state("sensor.dark_sky_icon_3d", "sleet") %}
          mdi:weather-snowy-rain
        {% elif is_state("sensor.dark_sky_icon_3d", "snow") %}
          mdi:weather-snowy
        {% elif is_state("sensor.dark_sky_icon_3d", "wind") %}
          mdi:weather-windy
        {% elif is_state("sensor.dark_sky_icon_3d", "fog") %}
          mdi:weather-fog
        {% elif is_state("sensor.dark_sky_icon_3d", "partly-cloudy-day") %}
          mdi:weather-partlycloudy
        {% elif is_state("sensor.dark_sky_icon_3d", "partly-cloudy-night") %}
          mdi:weather-partlycloudy
        {% else %}
          error
        {% endif %}

    forecast_4:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
        {{ date | timestamp_custom("%A") }}
      entity_id: sensor.time
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_4d.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_4d.state|round(0)}}°
      icon_template: >-
        {% if is_state("sensor.dark_sky_icon_4d", "clear-day") %}
          mdi:weather-sunny
        {% elif is_state("sensor.dark_sky_icon_4d", "clear-night") %}
          mdi:weather-night
        {% elif is_state("sensor.dark_sky_icon_4d", "cloudy") %}
          mdi:weather-cloudy
        {% elif is_state("sensor.dark_sky_icon_4d", "rain") %}
          mdi:weather-pouring
        {% elif is_state("sensor.dark_sky_icon_4d", "sleet") %}
          mdi:weather-snowy-rain
        {% elif is_state("sensor.dark_sky_icon_4d", "snow") %}
          mdi:weather-snowy
        {% elif is_state("sensor.dark_sky_icon_4d", "wind") %}
          mdi:weather-windy
        {% elif is_state("sensor.dark_sky_icon_4d", "fog") %}
          mdi:weather-fog
        {% elif is_state("sensor.dark_sky_icon_4d", "partly-cloudy-day") %}
          mdi:weather-partlycloudy
        {% elif is_state("sensor.dark_sky_icon_4d", "partly-cloudy-night") %}
          mdi:weather-partlycloudy
        {% else %}
          error
        {% endif %}

    forecast_5:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
        {{ date | timestamp_custom("%A") }}
      entity_id: sensor.time
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_5d.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_5d.state|round(0)}}°
      icon_template: >-
        {% if is_state("sensor.dark_sky_icon_5d", "clear-day") %}
          mdi:weather-sunny
        {% elif is_state("sensor.dark_sky_icon_5d", "clear-night") %}
          mdi:weather-night
        {% elif is_state("sensor.dark_sky_icon_5d", "cloudy") %}
          mdi:weather-cloudy
        {% elif is_state("sensor.dark_sky_icon_5d", "rain") %}
          mdi:weather-pouring
        {% elif is_state("sensor.dark_sky_icon_5d", "sleet") %}
          mdi:weather-snowy-rain
        {% elif is_state("sensor.dark_sky_icon_5d", "snow") %}
          mdi:weather-snowy
        {% elif is_state("sensor.dark_sky_icon_5d", "wind") %}
          mdi:weather-windy
        {% elif is_state("sensor.dark_sky_icon_5d", "fog") %}
          mdi:weather-fog
        {% elif is_state("sensor.dark_sky_icon_5d", "partly-cloudy-day") %}
          mdi:weather-partlycloudy
        {% elif is_state("sensor.dark_sky_icon_5d", "partly-cloudy-night") %}
          mdi:weather-partlycloudy
        {% else %}
          error
        {% endif %}

    forecast_6:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
        {{ date | timestamp_custom("%A") }}
      entity_id: sensor.time
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_6d.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_6d.state|round(0)}}°
      icon_template: >-
        {% if is_state("sensor.dark_sky_icon_6d", "clear-day") %}
          mdi:weather-sunny
        {% elif is_state("sensor.dark_sky_icon_6d", "clear-night") %}
          mdi:weather-night
        {% elif is_state("sensor.dark_sky_icon_6d", "cloudy") %}
          mdi:weather-cloudy
        {% elif is_state("sensor.dark_sky_icon_6d", "rain") %}
          mdi:weather-pouring
        {% elif is_state("sensor.dark_sky_icon_6d", "sleet") %}
          mdi:weather-snowy-rain
        {% elif is_state("sensor.dark_sky_icon_6d", "snow") %}
          mdi:weather-snowy
        {% elif is_state("sensor.dark_sky_icon_6d", "wind") %}
          mdi:weather-windy
        {% elif is_state("sensor.dark_sky_icon_6d", "fog") %}
          mdi:weather-fog
        {% elif is_state("sensor.dark_sky_icon_6d", "partly-cloudy-day") %}
          mdi:weather-partlycloudy
        {% elif is_state("sensor.dark_sky_icon_6d", "partly-cloudy-night") %}
          mdi:weather-partlycloudy
        {% else %}
          error
        {% endif %}
