---

- platform: yamaha
  name: Yamaha Receiver
  host: !secret yamaha_host
  source_ignore:
    - "HDMI1"
  source_names:
    HDMI2: "Custom"
    HDMI3: "Computer"
    HDMI4: "Playstation 4 Pro"
    Spotify: "Spotify"
    Airplay: "Airplay"
  zone_ignore:
    - "Zone_2"
  zone_names:
    Main_Zone: "Living Room"

- platform: philips_android_tv
  name: TV
  host: !secret philips_tv_host
  mac: 70:AF:24:BD:ED:A9
  username: !secret philips_tv_username
  password: !secret philips_tv_password
  favorite_channels_only: true
