---

- alias: 'Sync with Google Assistant'
  id: swga
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: google_assistant.request_sync
      data:
        agent_user_id: !secret google_agent_user_id

- alias: 'Get Events from IFTTT'
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'

- alias: 'Shelly Status Info at Start'
  id: ssias
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: mqtt.publish
      data:
        topic: 'shellies/command'
        payload: 'update'

- alias: Turn on guest restroom light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.guest_room_motion_sensor
    to: 'on'
  condition:
    condition: time
    after: '07:30'
    before: '23:30'
  action:
    service: switch.turn_on
    entity_id: switch.guest_room_switch

- alias: Turn on kids restroom light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.kids_shower_motion_sensor
    to: 'on'
  condition:
    condition: time
    after: '07:30'
    before: '23:30'
  action:
    service: switch.turn_on
    entity_id: switch.shower_switch
