---

- alias: 'Sync with Google Assistant'
  id: swga
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: google_assistant.request_sync
      data:
        agent_user_id: !secret google_agent_user_id

- alias: 'Sync with Google Assistant'
  id: shsync
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: mqtt.publish
      data:
        topic: "shellies/command"
        payload: "update"

- alias: 'Stop projection screen when it reaches 45 precent'
  id: prjstop
  trigger:
    platform: numeric_state
    entity_id: cover.projection_screen
    value_template: "{{ state.attributes.current_position }}"
    below: 45
  action:
    - service: cover.stop_cover
      data:
        entity_id: cover.projection_screen