---

- alias: 'Sync with Google Assistant'
  id: swga
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: google_assistant.request_sync
      data:
        agent_user_id: !secret google_agent_user_id

- alias: 'Sync Shellies'
  id: shsync
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: mqtt.publish
      data:
        topic: "shellies/command"
        payload: "update"

- alias: Turn on guest restroom light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.guest_room_motion_sensor
    to: 'on'
  condition:
    condition: time
    after: '07:30'
    before: '23:30'
  action:
    service: switch.turn_on
    entity_id: switch.guest_room_light

- alias: Turn on kids restroom light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.kids_shower_motion_sensor
    to: 'on'
  condition:
    condition: time
    after: '07:30'
    before: '21:00'
  action:
    service: switch.turn_on
    entity_id: switch.shower_light

- alias: Remind to close the office door when the Living Room air conditioner is turned on
  trigger:
    platform: time_pattern
    minutes: "/15"
  condition:
    - condition: state
      entity_id: climate.living_ro
      state:
        - 'cool'
        - 'heat'
    - condition: state
      entity_id: binary_sensor.office_door_sensor
      state: 'on'
    - condition: time
      after: '10:00'
      before: '21:00'
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.bedroom_speaker
        - media_player.kitchen_display
      data:
        volume_level: 0.6
    - service: tts.google_translate_say
      entity_id:
        - media_player.bedroom_speaker
        - media_player.kitchen_display
      data:
        message: 'Air conditioner is working, but office door is opened, please close it'

- alias: Lower all media players volume when time is 20:30
  trigger:
    platform: time
    at:
      - "20:30:00"
  action:
    - service: media_player.volume_set
      entity_id: media_player.yamaha_receiver_living_room
      data:
        volume_level: 0.5
    - service: media_player.volume_set
      entity_id:
        - media_player.living_room_home
        - media_player.living_room_speaker
        - media_player.kitchen_display
        - media_player.bedroom_speaker
      data:
        volume_level: 0.2
