---

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  customize: !include customize.yaml

# Default Homeassistant Configuration

config:
http:
person:
ssdp:
system_health:
zeroconf:
api:

frontend:
  themes:
    !include_dir_merge_named themes
  extra_html_url:
    - /local/hass-fontawesome-solid.html
    - /local/hass-fontawesome-regular.html
    - /local/hass-fontawesome-brands.html

cast:
  media_player:
    - host: !secret bedroom_home_mini_host
    - host: !secret living_room_home_host
    - host: !secret kitchen_display_host

# Text to speech
tts:
  - platform: google_translate
    service_name: google_translate_say
    base_url: !secret home_url

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named entities/scripts/
switch: !include_dir_merge_list entities/switches/
sensor: !include_dir_merge_list entities/sensors/
media_player: !include_dir_merge_list entities/media_players/
cover: !include_dir_merge_list entities/covers/
google_assistant: !include entities/google_assistant.yaml
rest_command: !include_dir_merge_named entities/rest_commands/

# Custom configuration

notify:
  - platform: html5
    name: Bar Home Notifier
    vapid_pub_key: !secret notif_prv_key
    vapid_prv_key: !secret notif_pub_key
    vapid_email: !secret email

mqtt:
  broker: k3s-master
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

smartir:

climate:
  - platform: sensibo
    api_key: !secret climate_api_key
  - platform: smartir
    name: Mazgan
    unique_id: living_room_ac
    device_code: 100
    controller_data: !secret broadlink_host

ifttt:
  key: !secret ifttt_api_key

# vacuum:
#   - platform: roomba
#     host: !secret roomba_host
#     username: !secret roomba_username
#     password: !secret roomba_password

device_tracker:
  - platform: netgear
    password: !secret arlo_password
    host: !secret arlo_host
    port: !secret arlo_port
    new_device_defaults:
      track_new_devices: true

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120

alarm_control_panel:
  - platform: aarlo

calendar:
  - platform: todoist
    token: !secret todoist_token
