---

version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          command: |
            sudo apt install git-secret
            sudo pip install yamllint homeassistant
      - run:
          command: |
            echo $GPG_KEY | base64 --decode >> /tmp/gpg.key
            gpg --import /tmp/gpg.key
            git secret reveal
      - run:
          command: |
            sudo yamllint .
            sudo hass --script check_config --config .
