---

- platform: template
  covers:
    projection_screen:
      friendly_name: "Projection Screen"
      device_class: shutter
      open_cover:
        service: cover.open_cover
        entity_id: cover.projection_screen_controller
      close_cover:
        service: cover.set_cover_position
        data:
          entity_id: cover.projection_screen_controller
          position: 45
      stop_cover:
        service: cover.stop_cover
        entity_id: cover.projection_screen_controller
      set_cover_position:
        service: cover.set_cover_position
        data_template:
          position: "{{ position }}"
      value_template: "{{ is_state('cover.projection_screen_controller', 'open') }}"
      icon_template: >-
        {% if is_state('cover.projection_screen_controller', 'open') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}

- platform: mqtt
  name: "Projection Screen Controller"
  device_class: shutter
  command_topic: "shellies/shellyswitch25-688A67/roller/0/command"
  position_topic: "shellies/shellyswitch25-688A67/roller/0/pos"
  set_position_topic: "shellies/shellyswitch25-688A67/roller/0/command/pos"
  availability_topic: "shellies/shellyswitch25-688A67/online"
  qos: 1
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  payload_available: "true"
  payload_not_available: "false"
  position_open: 100
  position_closed: 45
  optimistic: false

- platform: mqtt
  name: "Bedroom Cover"
  device_class: shutter
  command_topic: "shellies/shellyswitch25-68DE08/roller/0/command"
  position_topic: "shellies/shellyswitch25-68DE08/roller/0/pos"
  set_position_topic: "shellies/shellyswitch25-68DE08/roller/0/command/pos"
  availability_topic: "shellies/shellyswitch25-68DE08/online"
  qos: 1
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  payload_available: "true"
  payload_not_available: "false"
  position_open: 100
  position_closed: 0
  optimistic: false

- platform: mqtt
  name: "Living Room Cover"
  device_class: shutter
  command_topic: "shellies/shellyswitch25-692370/roller/0/command"
  position_topic: "shellies/shellyswitch25-692370/roller/0/pos"
  set_position_topic: "shellies/shellyswitch25-692370/roller/0/command/pos"
  availability_topic: "shellies/shellyswitch25-692370/online"
  qos: 1
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  payload_available: "true"
  payload_not_available: "false"
  position_open: 100
  position_closed: 0
  optimistic: false

- platform: mqtt
  name: "Laundry Room Cover"
  device_class: shutter
  command_topic: "shellies/shellyswitch25-692148/roller/0/command"
  position_topic: "shellies/shellyswitch25-692148/roller/0/pos"
  set_position_topic: "shellies/shellyswitch25-692148/roller/0/command/pos"
  availability_topic: "shellies/shellyswitch25-692148/online"
  qos: 1
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  payload_available: "true"
  payload_not_available: "false"
  position_open: 100
  position_closed: 0
  optimistic: false
