---

- platform: mqtt
  name: "Left Lamp"
  state_topic: "shellies/shelly1-68B498/relay/0"
  command_topic: "shellies/shelly1-68B498/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Right Lamp"
  state_topic: "shellies/shelly1-689AC4/relay/0"
  command_topic: "shellies/shelly1-689AC4/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: broadlink
  mac: !secret broadlink_mac
  switches:
    - name: "Family Room Light"
      command_on: !secret family_room_switch_on
      command_off: !secret family_room_switch_off
    - name: "Kitchen Light"
      command_on: !secret kitchen_switch_on
      command_off: !secret kitchen_switch_off
    - name: "Laundry Light"
      command_on: !secret laundry_switch_on
      command_off: !secret laundry_switch_off
    - name: "Food Corner Light"
      command_on: !secret food_switch_on
      command_off: !secret food_switch_off
    - name: "Office Light"
      command_on: !secret office_switch_on
      command_off: !secret office_switch_off
    - name: "Guest Room Light"
      command_on: !secret guest_room_switch_on
      command_off: !secret guest_room_switch_off
    - name: "Kids Switch"
      command_on: !secret kids_switch_on
      command_off: !secret kids_switch_off
    - name: "Shower Light"
      command_on: !secret shower_switch_on
      command_off: !secret shower_switch_off
    - name: "Room Shower Light"
      command_on: !secret room_shower_switch_on
      command_off: !secret room_shower_switch_off

