---

- platform: broadlink
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  timeout: 15
  switches:
    mazgan:
      friendly_name: "Mazgan"
      command_on: !secret mazgan_on
      command_off: !secret mazgan_off
    projector:
      friendly_name: "Projector"
      command_on: !secret projector_on
      command_off: !secret projector_off
