---

- platform: broadlink
  mac: !secret broadlink_mac
  switches:
    - name: "Kitchen Venta"
      command_on: !secret kitchen_venta_on
      command_off: !secret kitchen_venta_off
    - name: "Guest Room Venta"
      command_on: !secret guest_room_venta_on
      command_off: !secret guest_room_venta_off
